---
- name: Server setup for masters and workers
  hosts: all
  become: yes
  tasks:

    - name: Create user wolf
      ansible.builtin.user:
        name: wolf
        groups: sudo
        append: yes
        shell: /bin/bash

    - name: Configure sudo without password
      ansible.builtin.copy:
        dest: /etc/sudoers.d/wolf
        content: "wolf ALL=(ALL) NOPASSWD:ALL\n"
        mode: '0440'

    - name: Set hostname for nodes
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Update /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          192.168.4.197 master1
          192.168.4.196 master2
          192.168.4.195 master3
          192.168.4.194 worker1
          192.168.4.193 worker2

    - name: Copy SSH key for user wolf (authorized_keys like ssh-copy-id)
      ansible.posix.authorized_key:
        user: wolf
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519_vm.pub') }}"

    # --- Privātās atslēgas kopēšana ---

    - name: Ensure .ssh directory exists for wolf
      ansible.builtin.file:
        path: /home/wolf/.ssh
        state: directory
        owner: wolf
        group: wolf
        mode: '0700'

    - name: Copy private SSH key to wolf's home directory
      ansible.builtin.copy:
        src: ~/.ssh/id_ed25519_vm
        dest: /home/wolf/.ssh/id_ed25519_vm
        owner: wolf
        group: wolf
        mode: '0600'
    # ------------------------------------
    - name: Fix SSH config — replace PasswordAuthentication yes → no
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
        state: present
        backup: yes  # drošībai
    
    - name: Fix SSH config — replace PermitRootLogin yes → no
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin yes'
        line: 'PermitRootLogin no'
        state: present

    - name: Check if SSH config already matches desired settings
      ansible.builtin.shell: |
        grep -Fxq "PasswordAuthentication no" /etc/ssh/sshd_config &&
        grep -Fxq "PermitRootLogin no" /etc/ssh/sshd_config &&
        grep -Fxq "PubkeyAuthentication yes" /etc/ssh/sshd_config &&
        grep -Fxq "HostKey /etc/ssh/ssh_host_ed25519_key" /etc/ssh/sshd_config &&
        grep -Fxq "PubkeyAcceptedAlgorithms ssh-ed25519" /etc/ssh/sshd_config &&
        grep -Fxq "HostkeyAlgorithms ssh-ed25519" /etc/ssh/sshd_config
      register: ssh_config_ok
      failed_when: false
      changed_when: false

    - name: Configure SSH daemon only if settings differ
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        marker: "# {mark} ANSIBLE MANAGED BLOCK SSH"
        block: |
          PasswordAuthentication no
          PermitRootLogin no
          PubkeyAuthentication yes
          HostKey /etc/ssh/ssh_host_ed25519_key
          PubkeyAcceptedAlgorithms ssh-ed25519
          HostkeyAlgorithms ssh-ed25519
      when: ssh_config_ok.rc != 0

    - name: Restart SSH service
      ansible.builtin.service:
        name: ssh
        state: restarted

- name: K8s host prerequisites
  hosts: all
  become: yes

  tasks:

    - name: Load required kernel modules immediately
      ansible.builtin.modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Ensure kernel modules are loaded on boot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: '0644'

    - name: Configure sysctl params for Kubernetes
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables=1
          net.bridge.bridge-nf-call-ip6tables=1
          net.ipv4.ip_forward=1
        owner: root
        group: root
        mode: '0644'

    - name: Apply sysctl changes
      ansible.builtin.command: sysctl --system
      register: sysctl_output
      changed_when: "'Applying' in sysctl_output.stdout"
