---
- name: Server setup for masters and workers
  hosts: all
  become: yes
  tasks:

    - name: Create user wolf
      ansible.builtin.user:
        name: wolf
        groups: sudo
        append: yes
        shell: /bin/bash

    - name: Configure sudo without password
      ansible.builtin.copy:
        dest: /etc/sudoers.d/wolf
        content: "wolf ALL=(ALL) NOPASSWD:ALL\n"
        mode: '0440'

    - name: Set hostname for nodes
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Update /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          192.168.1.199 master1
          192.168.1.198 master2
          192.168.1.197 master3
          192.168.1.196 worker1
          192.168.1.195 worker2

    - name: Copy SSH key for user wolf (authorized_keys like ssh-copy-id)
      ansible.posix.authorized_key:
        user: wolf
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519_vm.pub') }}"

    # --- Privātās atslēgas kopēšana ---

    - name: Ensure .ssh directory exists for wolf
      ansible.builtin.file:
        path: /home/wolf/.ssh
        state: directory
        owner: wolf
        group: wolf
        mode: '0700'

    - name: Copy private SSH key to wolf's home directory
      ansible.builtin.copy:
        src: ~/.ssh/id_ed25519_vm
        dest: /home/wolf/.ssh/id_ed25519_vm
        owner: wolf
        group: wolf
        mode: '0600'
    # ------------------------------------
    - name: Fix SSH config — replace PasswordAuthentication yes → no
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
        state: present
        backup: yes  # drošībai
    
    - name: Fix SSH config — replace PermitRootLogin yes → no
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin yes'
        line: 'PermitRootLogin no'
        state: present

    - name: Check if SSH config already matches desired settings
      ansible.builtin.shell: |
        grep -Fxq "PasswordAuthentication no" /etc/ssh/sshd_config &&
        grep -Fxq "PermitRootLogin no" /etc/ssh/sshd_config &&
        grep -Fxq "PubkeyAuthentication yes" /etc/ssh/sshd_config &&
        grep -Fxq "HostKey /etc/ssh/ssh_host_ed25519_key" /etc/ssh/sshd_config &&
        grep -Fxq "PubkeyAcceptedAlgorithms ssh-ed25519" /etc/ssh/sshd_config &&
        grep -Fxq "HostkeyAlgorithms ssh-ed25519" /etc/ssh/sshd_config
      register: ssh_config_ok
      failed_when: false
      changed_when: false

    - name: Configure SSH daemon only if settings differ
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        marker: "# {mark} ANSIBLE MANAGED BLOCK SSH"
        block: |
          PasswordAuthentication no
          PermitRootLogin no
          PubkeyAuthentication yes
          HostKey /etc/ssh/ssh_host_ed25519_key
          PubkeyAcceptedAlgorithms ssh-ed25519
          HostkeyAlgorithms ssh-ed25519
      when: ssh_config_ok.rc != 0

    - name: Restart SSH service
      ansible.builtin.service:
        name: ssh
        state: restarted