---
- name: Izveidot HostPath direktoriju /mnt/awx-storage
  hosts: masters, workers
  become: true
  gather_facts: false

  tasks:
    - name: Izveidot HostPath direktoriju /mnt/awx-storage
      ansible.builtin.file:
        path: /mnt/awx-storage
        state: directory
        mode: '0777'
        owner: root
        group: root

# Fāze 2: AWX operatora un resursu izvietošana
- name: 2. AWX operatora un Kubernetes resursu izvietošana
  hosts: master1
  gather_facts: false

  tasks:
    # ───────────────────────────────────────────────
    # Helm operator
    # ───────────────────────────────────────────────
    - name: Pievienot AWX operatora Helm repozitoriju
      kubernetes.core.helm_repository:
        name: awx-operator
        repo_url: https://ansible-community.github.io/awx-operator-helm/

    - name: Atjaunināt helm repozitorijus
      ansible.builtin.command: helm repo update
      changed_when: true

    - name: Instalēt AWX operatoru
      kubernetes.core.helm:
        name: ansible-awx-operator
        chart_ref: awx-operator/awx-operator
        release_namespace: awx
        create_namespace: true
        state: present

    # ───────────────────────────────────────────────
    # Gaidām operatora podu
    # ───────────────────────────────────────────────
    - name: Gaidīt AWX operatora gatavību
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: awx
        label_selectors:
          - control-plane=controller-manager
      register: awx_operator_pods
      until: awx_operator_pods.resources | length > 0
      retries: 30
      delay: 10

    # ───────────────────────────────────────────────
    # StorageClass un PV
    # ───────────────────────────────────────────────
    - name: Izveidot StorageClass
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: local-storage-awx
          provisioner: kubernetes.io/no-provisioner
          volumeBindingMode: WaitForFirstConsumer

    - name: Izveidot PersistentVolume
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: postgres-pv-awx
          spec:
            capacity:
              storage: 10Gi
            accessModes:
              - ReadWriteOnce
            persistentVolumeReclaimPolicy: Retain
            storageClassName: local-storage-awx
            hostPath:
              path: /mnt/awx-storage

    # ───────────────────────────────────────────────
    # AWX Custom Resource
    # ───────────────────────────────────────────────
    - name: Izveidot AWX instanci
      kubernetes.core.k8s:
        state: present
        namespace: awx
        definition:
          apiVersion: awx.ansible.com/v1beta1
          kind: AWX
          metadata:
            name: ansible-awx
          spec:
            service_type: NodePort
            postgres_storage_class: local-storage-awx

    # ───────────────────────────────────────────────
    # Traefik IngressRoute un middleware
    # ───────────────────────────────────────────────
    - name: Izveidot redirect-to-https middleware (ja neeksistē)
      kubernetes.core.k8s:
        state: present
        namespace: awx
        definition:
          apiVersion: traefik.io/v1alpha1
          kind: Middleware
          metadata:
            name: redirect-to-https
          spec:
            redirectScheme:
              scheme: https
              permanent: true

    - name: Izveidot AWX HTTP → HTTPS redirect IngressRoute
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: traefik.io/v1alpha1
          kind: IngressRoute
          metadata:
            name: awx-http-redirect
            namespace: awx
          spec:
            entryPoints:
              - web
            routes:
              - match: Host(`awx.iloto.lldev`)
                kind: Rule
                middlewares:
                  - name: redirect-to-https
                services:
                  - name: ansible-awx-service
                    port: 80

    - name: Izveidot AWX HTTPS IngressRoute
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: traefik.io/v1alpha1
          kind: IngressRoute
          metadata:
            name: awx-https
            namespace: awx
          spec:
            entryPoints:
              - websecure
            routes:
              - match: Host(`awx.iloto.lldev`)
                kind: Rule
                services:
                  - name: ansible-awx-service
                    port: 80
            tls:
              secretName: iloto-wildcard-tls

# kubectl get svc -n awx
