---
- name: Import custom CA and wildcard certificates
  hosts: all
  become: yes

  vars:
    cert_dest_dir: "/root/"
    ca_certificates:
      - "latloto-ca.crt"
      - "latloto-intermediate-server-v1.crt"
      - "latloto-intermediate-server-v2.crt"
    wildcard_cert_name: "wildcard.iloto.lldev"

  tasks:
    - name: Ensure /root/ exists
      file:
        path: "{{ cert_dest_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy CA certificates
      copy:
        src: "loto/{{ item }}"
        dest: "{{ cert_dest_dir }}/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop: "{{ ca_certificates }}"

    - name: Copy wildcard certificate
      copy:
        src: "loto/{{ wildcard_cert_name }}.crt"
        dest: "{{ cert_dest_dir }}/wildcard.crt"
        owner: root
        group: root
        mode: '0644'

    - name: Copy wildcard key
      copy:
        src: "loto/{{ wildcard_cert_name }}.key"
        dest: "{{ cert_dest_dir }}/wildcard.key"
        owner: root
        group: root
        mode: '0600'
