---
# Master1 veic kubeadm init
- hosts: master1
  become: yes
  roles:
    - k8s-init-master

# Pārējie master mezgli pievienojas kontrolplānam (ar pauzi 60s)
- hosts: masters:!master1
  become: yes
  pre_tasks:
    - name: Gaidīt 60 sekundes pirms pievienošanās CP
      pause:
        seconds: 60
  roles:
    - k8s-join-controlplane

# Strādnieki pievienojas kā worker
- hosts: workers
  become: yes
  roles:
    - k8s-join-workers

# Master1 instalē weave
# - hosts: master1
#   become: yes
#   roles:
#     - weave

# Master1 instalē cilium
- name: KUBERNETES CILIUM CNI UZSTĀDĪŠANA (v1.18.4) UZ ARM64
  hosts: master1
  become: yes
  roles:
    - cilium