- name: MetalLB + Traefik + TLS Ingress
  hosts: masters
  become_user: root
  become: yes
  vars:
    metallb_namespace: metallb-system
    traefik_namespace: traefik
    vip: 192.168.1.190
    metallb_ip_range: "192.168.1.190-192.168.1.190"
    traefik_release: traefik
    tls_secret_name: wildcard-tls
    demo_host: hello.iloto.lldev
    cert_path: /root/certs # Attālais ceļš uz sertifikātiem

  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  tasks:

    # 1. Namespaces
    - name: Ensure MetalLB namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ metallb_namespace }}"
        state: present
      run_once: true

    # 2. MetalLB instalācija
    - name: Add MetalLB Helm repo
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb
        force_update: yes
      run_once: true

    - name: Install or upgrade MetalLB
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        release_namespace: "{{ metallb_namespace }}"
        create_namespace: false
        values:
          controller:
            webhook:
              create: false
        wait: yes
        wait_timeout: 300s
        force: yes
      run_once: true

    - name: Ensure metallb-memberlist secret exists
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: metallb-memberlist
            namespace: "{{ metallb_namespace }}"
          stringData:
            secretkey: "{{ lookup('password', '/dev/null length=128 chars=ascii_letters,digits') }}"
      run_once: true

    - name: Configure MetalLB Layer2 IP pool
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: layer2-pool
            namespace: "{{ metallb_namespace }}"
          spec:
            addresses:
            - "{{ metallb_ip_range }}"
      retries: 10
      delay: 5
      register: result
      until: result is not failed
      run_once: true

    - name: Create L2 Advertisement
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: layer2-advertisement
            namespace: {{ metallb_namespace }}
          spec:
            ipAddressPools:
            - layer2-pool
      run_once: true