---
- name: Install MetalLB and Configure Layer2
  hosts: masters
  become: yes
  vars:
    metallb_namespace: metallb-system
    vip: 192.168.1.190
    metallb_ip_range: "192.168.1.190-192.168.1.190"
    metallb_version: "0.14.3" # Ieteicamā stabila versija 

  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  tasks:
    # ===============================
    # 0. Tīrīšana un Namespaces
    # ===============================
    - name: Clean up existing failed MetalLB release (if any)
      kubernetes.core.helm:
        name: metallb
        release_namespace: "{{ metallb_namespace }}"
        state: absent
      ignore_errors: yes
      run_once: true

    - name: Ensure MetalLB namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ metallb_namespace }}"
        state: present
      run_once: true

    # ===============================
    # 1. MetalLB Instalācija
    # ===============================
    - name: Add MetalLB Helm repo
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb
        force_update: yes
      run_once: true

    - name: Install or upgrade MetalLB (v{{ metallb_version }})
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        release_namespace: "{{ metallb_namespace }}"
        create_namespace: false
        values: {}
        # LABOTS: Nomainīts nepareizais 'version' parametrs uz pareizo 'chart_version'
        chart_version: "{{ metallb_version }}" 
        wait: yes
        wait_timeout: 300s
        force: yes
      run_once: true

    - name: Ensure metallb-memberlist secret exists
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: metallb-memberlist
            namespace: "{{ metallb_namespace }}"
          stringData:
            # LABOTS: Izmantota standarta 'password' lookup funkcija, lai izvairītos no atkarības kļūdas
            secretkey: "{{ lookup('password', '/dev/null length=128 chars=ascii_letters,digits') }}"
      run_once: true

    # ===============================
    # 2. MetalLB Konfigurācija (IP Pool un L2 Advertisement)
    # ===============================
    - name: Configure MetalLB Layer2 IP pool
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: layer2-pool
            namespace: "{{ metallb_namespace }}"
          spec:
            addresses:
            - "{{ metallb_ip_range }}"
      run_once: true

    - name: Create L2 Advertisement
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: layer2-advertisement
            namespace: {{ metallb_namespace }}
          spec:
            ipAddressPools:
            - layer2-pool
      run_once: true