---
# 1. SERTIFIKĀTU SAGATAVOŠANA UZ MASTER1 UN KUBERNETES SECRETS IZVEIDE
- name: 1. Sertifikātu sagatavošana uz Master1 un Secret izveide
  hosts: masters
  # Šis solis tiek izpildīts TIKAI uz master1, lai apstrādātu failus
  # kur atrodas /root/certs
  run_once: true
  delegate_to: master1
  # Izmantojam 'wolf' lietotāju, bet nepieciešamas root (become: yes) atļaujas
  # lai piekļūtu /root/certs
  become: yes

# - name: 1. SERTIFIKĀTU SAGATAVOŠANA UN KUBERNETES SECRETS IZVEIDE
#   hosts: k8s_masters # Izpildām uz master-node-01, kur atrodas /root/certs
#   become: yes # Nepieciešams, lai piekļūtu /root/certs
# Ja izmanto k8s_master.ini

  tasks:
    - name: Apvienot sertifikātu ķēdi (wildcard + intermediate)
      ansible.builtin.shell: |
        cd /root/certs
        cat wildcard.iloto.lldev.crt latloto-intermediate-server-v2.crt latloto-intermediate-server-v1.crt > combined-chain.crt
      args:
        creates: /root/certs/combined-chain.crt # Idempotence

    - name: Izveidot 'traefik' vārda telpu (ja nepieciešams)
      kubernetes.core.k8s:
        name: traefik
        api_version: v1
        kind: Namespace
        state: present

    - name: Izveidot TLS Secret no sertifikātiem
      kubernetes.core.k8s:
        state: present
        namespace: traefik
        api_version: v1
        kind: Secret
        name: iloto-wildcard-tls
        data:
          # Šeit tiek ielādēti failu saturi, izmantojot bāzes64 kodējumu (automātiski)
          tls.crt: "{{ lookup('file', '/root/certs/combined-chain.crt') | b64encode }}"
          tls.key: "{{ lookup('file', '/root/certs/wildcard.iloto.lldev.key') | b64encode }}"
      # Pieņemam, ka ansible user var lasīt /root/certs failus.

# --------------------------------------------------------------------------------------

- name: 2. METALLB UZSTĀDĪŠANA (Layer 2)
  hosts: k8s_masters
  connection: local # Parasti labāk izpildīt uz Control Node, lai palaistu kubectl
  
  tasks:
    - name: Uzstādīt MetalLB manifestus
      kubernetes.core.k8s:
        state: present
        namespace: metallb-system
        src: https://raw.githubusercontent.com/metallb/metallb/v0.13.12/config/manifests/metallb.yaml

    - name: Pielietot MetalLB IP baseina un L2 konfigurāciju
      kubernetes.core.k8s:
        state: present
        src: "{{ playbook_dir }}/files/metallb-config.yaml" # Fails ar IP/L2 konfigurāciju

# --------------------------------------------------------------------------------------

- name: 3. TRAEFIK INGRESS CONTROLLER UZSTĀDĪŠANA (ar Helm)
  hosts: k8s_masters
  connection: local

  tasks:
    - name: Pievienot Traefik Helm repozitoriju
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: https://helm.traefik.io/traefik
        state: present

    - name: Uzstādīt Traefik, izmantojot vērtības failu
      kubernetes.core.helm:
        name: traefik
        chart: traefik/traefik
        release_namespace: traefik
        create_namespace: false
        state: present
        values_files:
          - "{{ playbook_dir }}/files/traefik-values.yaml" # Fails ar 192.168.4.190, shared-ip un tls config

# --------------------------------------------------------------------------------------

- name: 4. APLIKĀCIJAS UN INGRESS IZVIETOŠANA
  hosts: k8s_masters
  connection: local

  tasks:
    - name: Uzstādīt 'bitnami/nginx' (Hello World) ar Helm
      kubernetes.core.helm:
        name: hello-app
        chart: bitnami/nginx
        release_namespace: default
        state: present
        values:
          ingress:
            enabled: false # Ingress veidosim manuāli, nevis ar Helm

    - name: Izveidot Traefik Middleware HTTP -> HTTPS novirzīšanai
      kubernetes.core.k8s:
        state: present
        src: "{{ playbook_dir }}/files/redirect-middleware.yaml"

    - name: Izveidot Ingress resursu
      kubernetes.core.k8s:
        state: present
        src: "{{ playbook_dir }}/files/hello-ingress.yaml"