---
- name: Import custom CA certificate to all VMs (Rocky/Alma/CentOS)
  hosts: all
  become: yes

  vars:
    ca_cert_src: "ca.crt"   # Šeit jāieliek publiskais CA sertifikāts
    # RHEL-bāzētām sistēmām (Rocky, Alma, CentOS) CA sertifikāti tiek likti zem:
    ca_cert_dest_dir: "/etc/pki/ca-trust/source/anchors/"
    ca_cert_dest_file: "{{ ca_cert_dest_dir }}ca.crt"

  tasks:

    - name: Ensure the RHEL trust directory exists
      ansible.builtin.file:
        path: "{{ ca_cert_dest_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy CA certificate to trust store directory
      ansible.builtin.copy:
        src: "{{ ca_cert_src }}"
        dest: "{{ ca_cert_dest_file }}"
        owner: root
        group: root
        mode: '0644'
      notify: Update CA trust

    - name: Ensure ca-certificates package is present (in case it was removed)
      ansible.builtin.dnf:
        name: ca-certificates
        state: present

  handlers:
    - name: Update CA trust
      ansible.builtin.command: update-ca-trust extract
      # update-ca-trust extract ir RHEL-bāzēto sistēmu komanda, kas atjaunina CA krātuvi