---
- name: PREPARE + INSTALL Kubernetes v1.32 + CRI-O v1.32 on ALL Nodes (RHEL-based)
  hosts: all
  become: yes

  vars:
    KUBERNETES_VERSION: v1.32
    CRIO_VERSION: v1.32

  tasks:

    - name: Disable SWAP runtime
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Disable SWAP permanently in /etc/fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^(.+swap.+)$'
        replace: '# \1'

    - name: Install Base System Packages (dnf)
      ansible.builtin.dnf:
        state: present
        name:
          - curl
          - git
          - device-mapper-persistent-data
          - lvm2
          - yum-utils
          - container-selinux

    - name: Enable NTP time sync
      ansible.builtin.command: timedatectl set-ntp true

    - name: Load required modules (overlay and br_netfilter)
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Enable sysctl for Kubernetes networking
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: Apply sysctl params
      ansible.builtin.command: sysctl --system

    - name: Disable and Stop Firewalld (FW replacement on RHEL)
      ansible.builtin.systemd:
        name: firewalld
        enabled: no
        state: stopped
        daemon_reload: yes
      ignore_errors: yes # Firewalld var nebūt instalēts

    - name: Add Kubernetes Repository (RPM)
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/{{ KUBERNETES_VERSION }}/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/{{ KUBERNETES_VERSION }}/rpm/repodata/repomd.xml.key

    - name: Add CRI-O Repository (RPM)
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/cri-o.repo
        content: |
          [cri-o]
          name=CRI-O
          baseurl=https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ CRIO_VERSION }}/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ CRIO_VERSION }}/rpm/repodata/repomd.xml.key

    - name: Install Kubernetes + CRI-O packages (dnf)
      ansible.builtin.dnf:
        name:
          - cri-o
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Hold package versions (prevent mismatch)
      ansible.builtin.command:
        cmd: "dnf versionlock add kubelet kubeadm kubectl cri-o"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux'
      # 'versionlock' ir dnf/yum paplašinājums, tas jāinstalē atsevišķi, ja tas nav noklusējumā,
      # bet Ansible dnf modulis to atbalsta, izmantojot "disable_excludes", ja nav pieejams "versionlock" komandrindas rīks.
      # Tomēr, dnf versionlock ir visizplatītākais veids RHEL kloniem.

    - name: Enable + Start CRI-O
      ansible.builtin.systemd:
        name: crio
        enabled: yes
        state: started
        daemon_reload: yes # Pārlādē daemon

    - name: Enable kubelet (but not start, as kubeadm will start it later)
      ansible.builtin.systemd:
        name: kubelet
        enabled: yes
        state: stopped # Kubelet ir jābūt apstādinātam pirms kubeadm init/join